// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5bbb0doCisiix_3KHAfCPT2u2TE9XZeE',
    appId: '1:697453265854:web:553e6c5b0bbe1fa75f6fef',
    messagingSenderId: '697453265854',
    projectId: 'chat-app-rsa-aes',
    authDomain: 'chat-app-rsa-aes.firebaseapp.com',
    storageBucket: 'chat-app-rsa-aes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOyhngupPdIW-cfDsGXROgVs0XQhvTrZo',
    appId: '1:697453265854:android:fd14ce559a861c5e5f6fef',
    messagingSenderId: '697453265854',
    projectId: 'chat-app-rsa-aes',
    authDomain: 'chat-app-rsa-aes.firebaseapp.com',
    storageBucket: 'chat-app-rsa-aes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOyhngupPdIW-cfDsGXROgVs0XQhvTrZo',
    appId: '1:697453265854:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '697453265854',
    projectId: 'chat-app-rsa-aes',
    authDomain: 'chat-app-rsa-aes.firebaseapp.com',
    storageBucket: 'chat-app-rsa-aes.firebasestorage.app',
    iosBundleId: 'com.crypto.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOyhngupPdIW-cfDsGXROgVs0XQhvTrZo',
    appId: '1:697453265854:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '697453265854',
    projectId: 'chat-app-rsa-aes',
    authDomain: 'chat-app-rsa-aes.firebaseapp.com',
    storageBucket: 'chat-app-rsa-aes.firebasestorage.app',
    iosBundleId: 'com.crypto.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOyhngupPdIW-cfDsGXROgVs0XQhvTrZo',
    appId: '1:697453265854:android:fd14ce559a861c5e5f6fef',
    messagingSenderId: '697453265854',
    projectId: 'chat-app-rsa-aes',
    authDomain: 'chat-app-rsa-aes.firebaseapp.com',
    storageBucket: 'chat-app-rsa-aes.firebasestorage.app',
  );
}
